version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - leastprivilege  
- package-ecosystem: nuget
  directory: "/build"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
