blank_issues_enabled: false
contact_links:
  - name: Support Forum
    url: https://github.com/DuendeSoftware/Support/issues/new/choose
    about: The place for questions, support and feature requests
  - name: Create an Issue
    url: https://github.com/DuendeSoftware/foss/issues/new
    about: Create a new issue for a bug
