name: access-token-management\ci

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - access-token-management-v*
    paths:
    - .github/workflows/access-token-management-ci.yml
    - access-token-management/*
  pull_request:
    paths:
    - .github/workflows/access-token-management-ci.yml
    - access-token-management/*

env:
  DOTNET_NOLOGO: true

defaults:
  run:
    working-directory: access-token-management
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Build
      env:
        SignClientSecret: ${{ secrets.SignClientSecret }}
      run: ./build.ps1

    - name: Test report
      id: test-report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: test results
        path: access-token-management/test/AccessTokenManagement.Tests/TestResults/Test.trx
        reporter: dotnet-trx
        fail-on-error: true
        fail-on-empty: true

    - name: Install Sectigo CodeSiging CA certificates
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        sudo cp build/SectigoPublicCodeSigningRootCrossAAA.crt /usr/local/share/ca-certificates/
        sudo update-ca-certificates

    - name: Sign
      if: (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      env:
        SignClientSecret: ${{ secrets.SignClientSecret }}
      run: ./build.ps1 sign

    - name: Push packages to MyGet
      if: (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      run: dotnet nuget push artifacts\*.nupkg -s https://www.myget.org/F/duende_identityserver/api/v2/package -k ${{ secrets.MYGET }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      with:
        path: access-token-management/artifacts/*.nupkg
        compression-level: 0
        overwrite: true
        retention-days: 15