name: access-token-management-ci

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - access-token-management-v*
    paths:
    - .github/workflows/access-token-management-ci.yml
    - access-token-management/*
  pull_request:
    paths:
    - .github/workflows/access-token-management-ci.yml
    - access-token-management/*

env:
  DOTNET_NOLOGO: true

defaults:
  run:
    working-directory: access-token-management

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Build and test
      shell: pwsh    
      run: ./build.ps1