name: access-token-management-ci

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - access-token-management-v*
    paths:
    - .github/workflows/access-token-management-ci.yml
    - access-token-management/*
  pull_request:
    paths:
    - .github/workflows/access-token-management-ci.yml
    - access-token-management/*

env:
  DOTNET_NOLOGO: true

defaults:
  run:
    working-directory: access-token-management

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Build and Test
      shell: pwsh    
      run: ./build.ps1

    - name: Test Report
      id: test-report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: test results
        path: access-token-management/test/Tests/TestResults/Test.trx
        reporter: dotnet-trx
        fail-on-error: true
        fail-on-empty: true